### ISSUE TITLE
Perform ETL of Danesfield data and evaluate if they could be served by RGD 

### ISSUE THREAD

**Issue by aashish24** [girder/Danesfield#4]

**Comment by mvandenburgh** [comment]
I think this is closed by #8, right?

**Comment by AlmightyYakob** [comment]
Not exactly, as we're just serving 3D tiles as ChecksumFiles from the Danesfield API. If we want to effectively use RGD to serve all types of output files (not just 3D tiles, as that process is pretty straight forward), we may have to transform the ChecksumFiles into their corresponding downstream datatype (Raster, Image, etc.). So this would be the ETL.

I'm not actually sure what's required to view the other files in Cesium. If it turns out the endpoint that we added to serve 3D tiles also enables this behavior for all other types of files, then we can close this issue.

**Comment by mvandenburgh** [comment]
I've looked through each of the file types that the Danesfield algorithm outputs from the jacksonville point cloud, and all but one are supported by RGD:
.tif: `Image` (`rgd_imagery`)
.png: `Image` (`rgd_imagery`)
.obj: `PointCloud` (`rgd_3d`)
.ply: `PointCloud` (`rgd_3d`)
.geon: doesn't work with RGD, google suggests it's some kind of proprietary format ??

(copied from slack just to document this on the issue)
